### ISSUE TITLE
Snapshot reload timer

### ISSUE THREAD

**Issue by InTheta** [Marfusios/crypto-websocket-extensions#2]
Hi,

I can see potential issue with snapshot timer.
We could get stale data to trade on while getting snapshots.

Make this optional or add a bool stream to notify not to trade while getting snapshots.

Just an idea..

**Comment by Marfusios** [comment]
Hello, 

yea, good catch, snapshot reloading is disabled by default. 
Still evaluating how to implement it properly.

**Comment by InTheta** [comment]
I have done it so it gets snap shots on connect/reconnect.

But this is something I’ve yet to fully test.
