### ISSUE TITLE
OrderBookExample: getting all levels that caused the update

### ISSUE THREAD

**Issue by fdeste** [Marfusios/crypto-websocket-extensions#4]
Hello,
I'm trying to capture all levels that caused an OrderBookChange using the sample provided.
I'm not very familiar with c#, so I might be missing something. 
I am not able to find any level in the IOrderBookChangeInfo I'm getting: Quotes are updated but OrderBookLevel[] Levels { get; } seems empty.
Would you have any suggestion to get it to work?I'm just using the OrderBookExample provided in the repo.

Many thanks for your kind help and congratulations for the awesome package.

**Comment by Marfusios** [comment]
Hello @fdeste, 
yes, it is possible. Disabled by default because of performance, but you can enable it by: 
```
orderBook.DebugEnabled = true;
```
Then `Levels` will be filled correctly.

**Comment by fdeste** [comment]
Hello Mariusz,
it seems like thats enabled by default in your integration example, but
thats not working @ my installation.
Sorry for the messy indentation, im on mobile.

private static void ConfigureOptimized(IOrderBookLevel2Source source,
CryptoOrderBook orderBook)
{
orderBook.DebugEnabled = true;

}


Il gio 19 dic 2019, 7:38 PM Mariusz Kotas <notifications@github.com> ha
scritto:

**Comment by Marfusios** [comment]
![image](https://user-images.githubusercontent.com/3494837/71201903-4ddfa880-229b-11ea-86bb-8b08a36651a2.png)
Disabled on top, inside RunEverything() method

**Comment by fdeste** [comment]
Thank you!
