### ISSUE TITLE
Authenticated wallet / order snapshots via rest

### ISSUE THREAD

**Issue by InTheta** [Marfusios/crypto-websocket-extensions#6]
Hi,

Do you have any idea of where to implement authenticated rest calls to get wallet and orders snapshot.

Coinbase only sends orders and wallets on change via Websocket.

We need to add wallets and orders to CryptoWalletCollection and CryptoOrderCollection.

I originally had calls internally, but it may be best to get this data in the individual exchange libraries?

Any thoughts?

**Comment by Marfusios** [comment]
Hello @ColossusFX ,

you could use a similar approach as loading snapshot in order book sources. 
https://github.com/Marfusios/crypto-websocket-extensions/blob/master/src/Crypto.Websocket.Extensions/OrderBooks/Sources/BitmexOrderBookSource.cs#L126

**Comment by InTheta** [comment]
That’s what I have done.

Static method with api keys as params which then streams rest data normally.

👍🏽

**Comment by Marfusios** [comment]
ok, 
btw, avoid static methods with side effects, it is much cleaner and maintainable to have class methods because of testability, etc.
